name: AntiPortalStuck
version: '${version}'
main: net.reworlds.antiportalstuck.AntiPortalStuck
api-version: 1.19
authors: [ Statuxia ]
description: plugin to solve the problem of getting stuck in the portal during registration



commands:
  antiportalstuck:
    description:
      Used to change the plugin configuration.
    aliases: aps

permissions:
  antiportalstuck:
    default: op
